### ISSUE TITLE
Hac Logo covers entire page at certain width

### ISSUE THREAD

**Issue by radiantly** [codezoned/codezoned.github.io#44]
If the browser width is between 820-980px, the hac logo covers the entire page.
Screenshot:
![codezoned](https://user-images.githubusercontent.com/44368997/87319950-ebf0d400-c547-11ea-9206-9780ed6e8f18.png)

Tested on the latest versions of Firefox and Chromium on GNU/Linux.

**Comment by ionicc** [comment]
@radiantly Is this glitch sustaining even after a refresh?

**Comment by radiantly** [comment]
Yes, it is persistent even after a hard refresh.

**Comment by ionicc** [comment]
@radiantly You are open to propose a PR to fix this issue. If you want to do it, I'll assign this issue to you!

**Comment by ionicc** [comment]
@radiantly Seems like you've opened the http version of the website. Can you see if this is happening in https://hac.codezoned.com

**Comment by radiantly** [comment]
Same thing happens with the https version.

> You are open to propose a PR to fix this issue. If you want to do it, I'll assign this issue to you!

Sounds good, I'll investigate and open a PR.

**Comment by ionicc** [comment]
Great! @radiantly, I'll assign this issue to you

**Comment by swaaz** [comment]
It's not a glitch, when you change the dimension using inspect window it cannot fit everything but when you fix the dimension and reload the page it will load everything according to the dimension

**Comment by radiantly** [comment]
@swaaz I'm not using inspect element to change the width. I use my browser side by side with another applicatoon, and at this width the logo appears to show up in the center. Are you unable to reproduce?

**Comment by swaaz** [comment]
@radiantly I have no idea why they used static CSS in JS. I think @Aniket-Mishra is the right person to answer this question.
