### ISSUE TITLE
Team is not visible in the Nav Bar.

### ISSUE THREAD

**Issue by saswatsamal** [codezoned/codezoned.github.io#66]
Recently I checked into the website of HAC and noticed that the **Team** option in the navbar is hidden by the MLH Banner.

Check the below image for more reference.

![image](https://user-images.githubusercontent.com/39031660/89442267-2545e980-d76c-11ea-9fc9-a5554b4696f1.png)

**Comment by Avinash9k5r** [comment]
I am willing to work on this issue, you can assign me to this issue.
